metadata:
  name: slack-standup-random-master
  description: Select a random host for your standup ceremony and announce it on a slack channel.
  labels:
    #
    # either one of the following product, platform, practice.
    # See https://adgear.atlassian.net/wiki/spaces/ENG/pages/19146211708/Product+-+Platform+-+Practice    #
    stack: Ruby
    product: dsp
    #
    # Both jira-project and jira-board can be extract from from your Jira project board URL.
    # For instance, in https://adgear.atlassian.net/jira/software/c/projects/RI/boards/180    # project is RI, and board 180.
    #
    jira-project: SDSP
    jira-board: 182
    #
    # If spec.type is service or website, whether or not it is accessible outside the Samsung network
    public: false
    #
    # Whether or not this repo is maintained for a component which processes sensitive data
    # See  https://adgear.atlassian.net/wiki/spaces/INFOSEC/pages/2300969047/AdGear+-+Cybersecurity+Due+Diligence#Glossary    sensitive: true
  links:
    # Here is any link you feel is worth sharing. A confluence page for your component group is a good candidate.
    - url: https://adgear.atlassian.net/l/cp/9kD8ZGRe
      title: SDSP-API Confluence Page
  owner: cg-maintainers-dsp-api
  # Here are the types
  # service: is of course a system running on a workload instance, listening for requests at a particular port over a network, serving response in various payload.
  # library: is a component used by one or many other component(s).
  # tool: is a facility used as part of (development/deployment) workflows, generally involving an interactive UI (console or else). Could be a script, a CLI tool, etc.
  # infrastructure: is any piece of code to build infrastructure, with various level of abstraction. Terraform, salt are good candidate.
  type: library
  lifecycle: decommissioned
